
# Railway.com Configuration for Insurance AI System
# This file defines the deployment configuration for Railway.com

[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python railway_safe.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Service Configuration
[[services]]
name = "insurance-ai-api"
source = "."
domains = ["insurance-ai-api.railway.app"]

[services.variables]
# Application Configuration
PORT = "8080"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"

# Database Configuration (Railway provides these automatically)
# DATABASE_URL is provided by Railway PostgreSQL service
# REDIS_URL is provided by Railway Redis service

# AI Configuration (Set these in Railway dashboard)
# OPENAI_API_KEY = "your_openai_key"
# ANTHROPIC_API_KEY = "your_anthropic_key"
# AI_PROVIDER = "openai"
# AI_MODEL = "gpt-3.5-turbo"

# Security Configuration
# SECRET_KEY = "your_secret_key"
# JWT_SECRET_KEY = "your_jwt_secret"

# Institution Configuration
INSTITUTION_ID = "default"
ENABLE_AUTO_MIGRATE = "true"

# Performance Configuration
WORKERS = "4"
MAX_CONNECTIONS = "100"
CONNECTION_TIMEOUT = "30"

# Feature Flags
ENABLE_AI_FEATURES = "true"
ENABLE_CACHING = "true"
ENABLE_METRICS = "true"
