
# This file configures the PostgreSQL database on Railway.com
# Railway.com automatically provides environment variables for database connection

# Application Configuration
PORT=8000
NODE_ENV="production"

# Enable automatic migrations on deploy
ENABLE_AUTO_MIGRATE=true
